### ISSUE TITLE
Work well in plain text. but not HTML body.

### ISSUE THREAD

**Issue by iblogbox** [ykarpovich/msg.reader#1]
Very good work for Javascript. but It does not display correctly HTML body in the MSG file.

**Comment by ykarpovich** [comment]
Hi,

First of all it was developed to extract attachment on client-side and send just selected files.
But we able to discuss html-view support in case if needed for you or somebody else.

Thanks for your interest!

**Comment by nestoru** [comment]
Excellent work I would say. Supporting msg format from JS is a must!

Extracting html is very important. In fact the demo page fails to parse the msg in full when html is included. Is it difficult to enhance the library to support that? Perhaps the author can share some ideas?

Best regards, - Nestor
