### ISSUE TITLE
not able to get sender email

### ISSUE THREAD

**Issue by saniljain05** [ykarpovich/msg.reader#10]
When I am copying the mail from sent folder, I am not able to get the sender email in the parsed data. Any help?

**Comment by saniljain05** [comment]
can anyone please help? It is very urgent.

**Comment by ykarpovich** [comment]
Hi,
Do you have any example with this issue?

**Comment by JefinDX** [comment]
Hi, 'sender email' (`fileData.senderEmail`) is not getting defined if the .msg mail body text format is of HTML. Working properly only if the outlook email text is formatted as 'Plain Text'.

**Issue Screenshot**
![image](https://user-images.githubusercontent.com/56828393/142250912-f06d5845-0dee-463d-b2e0-1f12fa30c875.png)
