### ISSUE TITLE
Unable to read body on certain msg files.

### ISSUE THREAD

**Issue by alexcarter404** [ykarpovich/msg.reader#14]
On certain msg files I am unable to read the body with this plugin. 

When uploading the attached to the example site at https://ykarpovich.github.io/msg.reader/examples/example.html the body cannot be read. 

When opening with outlook the msg file is in tact and perfectly readable. Is there some sort of difference in this file compared to others?

[test-email.zip](https://github.com/ykarpovich/msg.reader/files/3275559/test-email.zip)

**Comment by alexcarter404** [comment]
After looking further into this, it seems that the reader cannot read msg files that only have a HTML body (and not RTF/Plain text).

Is it possible to update to read the HTML body content?

**Comment by ykarpovich** [comment]
In your case the latest version will be work as expected.

You can try https://ykarpovich.github.io/msg.reader/examples/example.html with test-email.msg from archive.

But in general this approach has a lot of issues. 
Please check https://github.com/ykarpovich/msg.reader/issues/5
