### ISSUE TITLE
Use remote Jquery

### ISSUE THREAD

**Issue by 1Jesper1** [ykarpovich/msg.reader#15]
https://github.com/ykarpovich/msg.reader/blob/c3bd6ee66aad5f8e3ffc9b035c273daa8700dd51/examples/example.html#L75

Use https:// instead of file://
https://code.jquery.com/jquery-1.12.0.min.js

**Comment by ykarpovich** [comment]
I've changed to 'https://' in order to be able use the example from local box without any app/web server or file changing.

By the way, '//' it's not the same as 'file://'. It's called a Protocol-relative URL

Cheers!
