### ISSUE TITLE
Download attachment with extension

### ISSUE THREAD

**Issue by 1Jesper1** [ykarpovich/msg.reader#16]
It would be great to download the attachment with the specified extension.

**Comment by TomasHubelbauer** [comment]
I believe this line in the example shows how:

https://github.com/ykarpovich/msg.reader/blob/master/examples/example.html#L145

You can get the created object URL and set it as a `src` attribute of an HTML `a` element and then set the `download` attribute of the element to the file name of the attachment. Clicking on the anchor will then initiate a download in the browser:

See https://stackoverflow.com/a/16316830/2715716

**Comment by 1Jesper1** [comment]
@TomasHubelbauer Thanks, but I mean something else:
Now the type of the file is always set to `{type: "application/octet-stream"}`
I would be great to set the type to the extension of the attachment, like "file1.png" then the type needs to be "{type: "image/png"}".

**Comment by TomasHubelbauer** [comment]
I see! Hopefully the MIME type is stored in the MSG file alongside the attachment and can be extracted, otherwise one would have to ship a lookup table from extension/signature bytes to the MIME value. Good feature request, sorry the above didn't help, I'll be watching this thread, too, to see if this will get supported.

**Comment by ykarpovich** [comment]
I've added MIME type parsing for attachments.

But based on my statistics this field really rarely has appropriate value.

@1Jesper1 if you want to stable and predictable solution use approach proposed by @TomasHubelbauer "lookup table from extension/signature bytes to the MIME value". 

The `attachment.extension` field in most cases has a valid attachment extension like `.pdf`, `.docx`, etc.
