### ISSUE TITLE
Any way to create writer not reader

### ISSUE THREAD

**Issue by kdfwow64** [ykarpovich/msg.reader#19]
I'm trying convert html to msg.
Any way to create it easily?
Thanks

**Comment by ykarpovich** [comment]
Hi,
Do you really need to create .msg with JS? Java/C#/... are not acceptable?

**Comment by kdfwow64** [comment]
Nope only jS

**Comment by kdfwow64** [comment]
Hello
So could you provide me the solution please?
Thanks

**Comment by kdfwow64** [comment]
I did it myself.
:)

**Comment by thuanguyen1602** [comment]
how did you do that @kdfwow64 ?

**Comment by kdfwow64** [comment]
I analysised the msg file structure and replaced some parts

**Comment by thuanguyen1602** [comment]
can you give me your code? please

**Comment by thuanguyen1602** [comment]
![image](https://user-images.githubusercontent.com/39271788/60110784-da9b2500-9796-11e9-8358-57751697be44.png)
I always get this error, how to fix it?

**Comment by kdfwow64** [comment]
Because the file structure is broken

**Comment by kdfwow64** [comment]
So first
you need to have sample msg in your code

**Comment by thuanguyen1602** [comment]
do you use skype? please help me.
my skype: quoc.thuan1602@gmail.com
