### ISSUE TITLE
Body doesn't always return, getting unit8array.

### ISSUE THREAD

**Issue by EvanHuxley** [ykarpovich/msg.reader#24]
When parsing files most the time the turn out as expected. Yet other times they will return as a standard unit8array that I can't parse.
![unit8array](https://user-images.githubusercontent.com/44485030/76237719-1848bc80-6205-11ea-9eb4-c5fec2cc0f6f.png)

**Comment by bluefire2121** [comment]
That's normal. Uint8Arrays are Buffers. Buffers can be converted into Files. 

Uint8Array -> Blob -> File

**Comment by paulsonantajo** [comment]
@EvanHuxley How did you handle this Uint8Array issue. I am having same issue in my NodeJS application.

**Comment by EvanHuxley** [comment]
The conversion didn't work, I migrated to @freiraum/msgreader https://www.npmjs.com/package/@freiraum/msgreader

**Comment by paulsonantajo** [comment]
@EvanHuxley  Same result after migrating @freiraum/msgreader :(

**Comment by paulsonantajo** [comment]
This is the way to go https://github.com/HiraokaHyperTools/msgreader
