### ISSUE TITLE
JS error in example

### ISSUE THREAD

**Issue by adjenks** [ykarpovich/msg.reader#9]
When I load a msg file on the demo page: https://ykarpovich.github.io/msg.reader/examples/example.html

I get:

> TypeError: fileData.body.substring is not a function[Learn More] example.html:141:33

Using FireFox 66.

**Comment by adjenks** [comment]
It appears to only give the error with a particular email. I tried another email and it worked.

**Comment by adjenks** [comment]
Weird.. I'm getting weird bugs. I'll try to supply a sample file, but I don't want to share the email that is giving the error....

**Comment by ykarpovich** [comment]
It's so strange...

I've double-checked with Chrome 73 and Firefox 66.0.2. I have no one error.

I guess only email example (maybe dummy, but with error as original) helps us to solve the problem.

**Comment by adjenks** [comment]
I'm sorry, I can't recreate the error with a non-confidential email. I'll post one if I can find one at a later date.

**Comment by jagant11** [comment]
I'm also facing the same issue, Unit8Array is returned as body. please find attached for sample email with the issue.

[3113.xlsx.zip](https://github.com/ykarpovich/msg.reader/files/3119886/3113.xlsx.zip)

**Comment by ykarpovich** [comment]
@jagant11 @adjenks 
Please try this version
https://ykarpovich.github.io/msg.reader/examples/example.html

**Comment by adjenks** [comment]
I think it appears to work. I'm not sure if I'm using the same email I tested with before, but I haven't had trouble with any. Before I had trouble with several.
